#!/bin/bash
# shellcheck disable=all

#! 	###############################################################################
#! 	#! ALL VARIABLES, SUBSTITUTIONS AND SWITCHES WE WISH TO PROGRAMMATICALLY USE
#! 	#! IN THE ARGUMENT FILE ARE DEFINED HERE.
#! 	# TODO VARNAME + VARNAMEdesc WILL AUTO POPULATE DOCUMENTATION AND ARGFILES.
#! 	# TODO PARTIAL, NOT QUITE COMPLETE
#! 	###############################################################################
#! RESORT THIS FILE USIING THIS COMMAND: cat ./VARLIST |grep -siv "#!" | LC_ALL=C sort -u -o ./VARLIST.SORTED

#_FIXD_DIR_TEMPLATE_A_="$(echo -e "$_DIRSTART_$_DSTDIR_/$_MAKE_$_ANDROIDMANUFACTURER_$_MODEL_$_ANDROIDMODEL_$_XIAOMIPRODUCTNAME_/$_EXT_/$_YEARMONTH_")"
#_FIXD_DIR_TEMPLATE_Adesc_="#TBD"
#_FIXD_DIR_TEMPLATE_B_="$(echo -e "$_DIRSTART_$_DSTDIR_/$_MAKE_$_ANDROIDMANUFACTURER_$_MODEL_$_ANDROIDMODEL_$_XIAOMIPRODUCTNAME_/$_EXT_/$_YEARMONTH_")"
#_FIXD_DIR_TEMPLATE_C_="$_DIRSTART_$_DSTDIR_/$_MAKE_$_ANDROIDMANUFACTURER_$_MODEL_$_ANDROIDMODEL_$_XIAOMIPRODUCTNAME_/$_EXT_/$_YEARMONTH_"
#_FIXD_DIR_TEMPLATE_C_="\$_DIRSTART_\$_DSTDIR_/\$_MAKE_\$_ANDROIDMANUFACTURER_\$_MODEL_\$_ANDROIDMODEL_\$_XIAOMIPRODUCTNAME_/\$_EXT_/\$_YEARMONTH_"
#_FIXD_DIR_TEMPLATE_D_="\$DIRSTART\$DSTDIR/\$MAKE\$ANDROIDMANUFACTURER\$MODEL\$ANDROIDMODEL\$XIAOMIPRODUCTNAME/\$EXT/\$YEARMONTH"
#_FIXD_DIR_TEMPLATE_E_="$DIRSTART$DSTDIR/$MAKE$ANDROIDMANUFACTURER$MODEL$ANDROIDMODEL$XIAOMIPRODUCTNAME/$EXT/$YEARMONTH"
_FIXD_NAME_TEMPLATE_A_="$(echo -e "$_FNAMESTART_$_SDATEFULL_$_IMAGESIZE_$_KEEPNAME_$_COUNTER_.$_EXT_")"
_FIXD_NAME_TEMPLATE_Adesc_="#TBD"
_ADDTAG_IMAGEHASH_="$(echo -e "-api\nImageHashType=$hashALGO\n-XMP:OriginalImageHash<ImageDataHash")"
_ADDTAG_IMAGEHASHdesc_="#* Creates imagehash tag."
_ADDTAG_PRESERVEDFILENAME_="-XMP-xmpMM:PreservedFileName<filename"
_ADDTAG_PRESERVEDFILENAMEdesc_="#* Adds the PreservedFileName tag."
_ADDTAG_ORIGINALFILENAME_="-XMP-getty:OriginalFilename<filename"
_ADDTAG_ORIGINALFILENAMEdesc_="#* Adds the OriginalFileName tag."


_ANDROIDMANUFACTURER_='${Keys:AndroidManufacturer;$_="[$_]"}'
_ANDROIDMANUFACTURERdesc_="#* Manufacturer"
_ANDROIDMODEL_='${Keys:AndroidModel;$_="[$_]"}'
_ANDROIDMODELdesc_="#* Model of android phone."
_COUNTER_='%+3c'
_COUNTERdesc_="#* Counter (Filename collision avoidance.)"
_DDATEFORMAT_="$(echo -e "-d\n%Y-%m-%d_%H.%M.%S__")"
_DDATEFORMATdesc_="#* (Prefer per dir option) -d/-dateFormat - Format for date/time values"
_DIRSTART_="-Directory<"
_DIRSTARTdesc_="#* Directory output destination start command."
_DSTDIR_="$DSTDIR"
_DSTDIRdesc_="#* DESTINATION DIRECTORY: OUTPUT directory for processed and renamed images"
_EXECUTE_="-execute"
_EXECUTEdesc_="#* RUN EVERYTHING UP TO HERE AS A SPECIFIC COMMAND SET"
_EXTLIST_="$EXTList"
_EXTLISTdesc_="#* Extensions to work on"
_EXT_='%e'
_EXTdesc_="#* File Extension"
_EZ_SETTINGS_META_="$(echo -e "$_SRCDIR_\n-execute\n")"
_EZ_SETTINGS_METAdesc_="#TBD"
_EZ_SETTINGS_PROTO_="$(echo -e "-m\n-P\n-q\n-q\n$_EXTLIST_\n--ext\nxmp\n-tagsfromfile\n-overwrite_original\n")"
# EZ_SETTINGS_PROTO=$_VERBOSE_, $_SUPRESSMINERR_,$_PRESERVE_, $_QUIET_, $_QUIET_, $_EXTLIST_, $_NOXMP_, $_GETTAGSFROMCURRENTFILE_, $_WRITEOVERFILE_

_EZ_SETTINGS_PROTOdesc_="#TBD"
_FILEORDERFILENAME_="$(echo -e "-fileOrder\n-FileName")"
_FILEORDERFILENAMEdesc_="#* Process in order of filename. Slow, dont use if possible."
_FMTLINE_="#############################################################################################################################"
_FNAMESTART_='-filename<'
_FNAMESTARTdesc_="#* Rename/move starting with SmartDate function included in the config that came with this script."
_GETTAGSFROMCURRENTFILE_="$(echo -e "-tagsfromfile\n")"
_GETTAGSFROMCURRENTFILEdesc_="#* GETS / SETS TAGS FROM CURRENT FILE "
_HASHALGORITHM_="${hashALGO}"
_HASHALGORITHMdesc_="#* Algorithm for creating the XMP:OriginalImageHash tag."
_IMAGESIZE_='${ImageSize;$_="[$_]"}'
_IMAGESIZEdesc_="#* Image Size composite tag"
_KEEPNAME_="$exifToolBaseNameSeperator\$basename"
_KEEPNAMEdesc_="#* Blank unless -k keepname option enabled, Seperator + original filename if switch set"
_MAKE_='${Make;$_="[$_]"}'
_MAKEdesc_="#* Make of Android phone tag."
_MODEL_='${Model;$_="[$_]"}'
_MODELdesc_="#* Model of camera/phone"
_NOEXIFDEST_="NO-EXIF"
_NOEXIFDESTdesc_="#* FOLDER NAME FOR NOEXIF DESTINATION DIRECTORY: OUTPUT directory for items without EXIF."
_NOXMP_="$(echo -e "--ext\nxmp")"
_NOXMPdesc_="#* DO NOT WORK ON XMP FILES # Don't process xmp files, strangely enough used mostly to process xmp files.. lol.. "
_PRESERVE_="-P"
_PRESERVEdesc_="#* (-P / -preserve) Preserve file modification date/time"
_QUIET_="$(echo -e "-q")"
_QUIETdesc_="#* Quieter output, put twice for very quiet. shhbbyisok"
_RECURSE_="${RECURSE}"
_RECURSEdesc_="#* Recurse. If recurse switch set, this will be -r, otherwise null/empty. "
_SDATEFULL_='${SmartDate;DateFmt("%Y-%m__%d_%H.%M.%S__")}'
_SDATEFULLdesc_="#* 2020-10-02_14.01.31__ SmartDate full output, used for filename usually."
_SHHBBYISOK_="$(echo -e "-m\n-q\n-q")"
_SHHBBYISOKdesc_="#* -m -q -q Supress minor errors and super quiet shortcut tag."
_SRCDIR_="$SRCDIR"
_SRCDIRdesc_="#* SOURCE DIRECTORY: INPUT directory containing unprocessed media."
_SRCFILE_EXT_XMP_="$(echo -e "-srcfile\n%d%f.%e.xmp")"
_SRCFILE_EXT_XMPdesc_="#* DIRECT ACTIONS TO FILENAME.EXT.XMP THIS FILE INSTEAD OF CURRENT FILE"
_SRCFILE_XMP_="$(echo -e '-srcfile\n%d%f.xmp')"
_SRCFILE_XMPdesc_="#* DIRECT ACTIONS TO FILENAME.XMP THIS FILE INSTEAD OF CURRENT FILE"
_SUPRESSMINERR_="-m"
_SUPRESSMINERRdesc_="#* Suppress minor errors, if used, must be used equally (or none) on XMP + media argfiles. Otherwise problems."
_VERBOSE_=" "
_VERBOSEdesc_="# When verbose switch set, this will be -v[0...5], 5 being most verbose. Set by VLevel "
_WRITEMODE_CREATE_INSERTMISSING_="$(echo -e "-wm\ncg")"
_WRITEMODE_CREATE_INSERTMISSINGdesc_="#* write mode CREATE AND ADD ONLY NEW TAGS "
_WRITEOVERFILE_="-overwrite_original"
_WRITEOVERFILEdesc_="#TBD"
_XIAOMIPRODUCTNAME_='${Keys:XiaomiProductMarketname;$_="[$_]"}'
_XIAOMIPRODUCTNAMEdesc_="#* Phone name tag from Xiaomi"
_YEARMONTH_='${SmartDate;DateFmt("%Y.%m-[%B]")}'
_YEARMONTHdesc_="#* SmartDate function located in config"
_YEAR_='${SmartDate;DateFmt("%Y")}'
_YEARdesc_="#* YEAR Folder"
